### ISSUE TITLE
Can't Process Images in the Init Phase?

### ISSUE THREAD

**Issue by VimislikArt** [Gouvernathor/renpy-ChromaGlitch#1]
This is working fine with "at glitch" and "at chromatic_offset", but when I try to use the methods to define the image or show it as an expression (I just swapped out beautifulcharacter angry with eileen happy), I get error messages that seem to imply that it can't process these images in the init phase.

I included the full tracebacks below for both of these issues.

[traceback_expression.txt](https://github.com/Gouvernathor/renpy-ChromaGlitch/files/7964983/traceback_expression.txt)
[traceback_image.txt](https://github.com/Gouvernathor/renpy-ChromaGlitch/files/7964984/traceback_image.txt)

**Comment by Gouvernathor** [comment]
Yeah, that's normal actually because my examples were wrong. I use a weird way of detecting the size of the image it's applied to, so basically ~~it can't work when defining images. Sorry, I'll update the readme.~~
Edit : actually you still can, just not that way and it's a tad longer (takes two lines instead of one). See the updated readme for more details.

As for the `expression` version, I can't reproduce your bug (using a string naming a good image works fine, and using a non-existing image it doesn't return the bug you do), but I think I nailed the issue. It's a single-line update. Can you insert this line before the `cwidth, cheight` line and tell me if the bug is solved ?
```py
child = renpy.easy.displayable_or_none(child)
```

**Comment by VimislikArt** [comment]
Yup!  That's working on my end for the expression version, and the workaround for image definition is working great!

What I really like about how you set up the glitch is that it randomizes the line separations, so in animation, it looks AMAZING, but to get it to work functionally, it's best used as an image definition:

image eileen glitched:
    At("eileen happy", glitch)
    pause 0.2
    At("eileen happy", chromatic_offset)
    pause 0.2
    At("eileen happy", glitch)
    pause 0.1
    At("eileen happy", chromatic_offset)
    pause 0.1
    At("eileen happy", glitch)
    pause 0.3
    At("eileen happy", chromatic_offset)
    pause 1.0
    repeat

This gives you a periodically randomized glitch, like this:

https://user-images.githubusercontent.com/97647421/151710676-792e9297-b7e1-4195-80e8-a081fbb38b0a.mp4

**Comment by Gouvernathor** [comment]
That's awesome !

**Comment by Gouvernathor** [comment]
Heads-up : I fixed the glitch using the cdd technique, which makes the ATL workaround unnecessary : the `image glitched = glitch("eileen")` now works.
