### ISSUE TITLE
Attempting to use animated-glitch transform results in the image affected showing for a breif period without glitching before showing the next image/scene

### ISSUE THREAD

**Issue by StarGarnet03** [Gouvernathor/renpy-ChromaGlitch#6]
I am assuming that animated-glitch is supposed to work like a regular transform, and, as such, have been attempting to use it that way. Here is the code that I am using at the moment:
`show Razlookingatyou at animated_glitch`

In this case, "Razlookingatyou" is my displayable, a simple PNG image in my images folder. I have no problem with the other two transforms, as replacing "animated_glitch" with "glitch" or "squares_glitch" in the code above works.

I have noticed, however, that in the .rpy file of the transform, animated_glitch is labeled as `class animated_glitch(glitch)`, while the other two are labeled as `renpy.Displayable` within the parentheses and I'm not quite sure why. Replacing `glitch` with `renpy.Displayable` causes this exception to occur:
![image](https://github.com/Gouvernathor/renpy-ChromaGlitch/assets/129735169/88725ae7-c26c-4478-a78c-54017ad775f8)

Help will be much appreciated!

**Comment by Gouvernathor** [comment]
glitch inherits from renpy.Displayable, so when animated_glitch inherits from glitch, it indirectly inherits from renpy.Displayable. It relies and tweaks on the glitch class's behavior. If you remove the glitch's sruff it relies on, it won't work.

I'm more interested in the behavior you find problematic, rather than the consequences of your attempt at fixing it.
If you read the readme file, I think it indicates that the first frame displayed by animated_glitch will be unglitched, and then toggle randomly between glitched and unglitched frames.
I suggest you try to fully understand how the transforms are supposed to work before flagging an issue.

**Comment by StarGarnet03** [comment]
> glitch inherits from renpy.Displayable, so when animated_glitch inherits from glitch, it indirectly inherits from renpy.Displayable. It relies and tweaks on the glitch class's behavior. If you remove the glitch's sruff it relies on, it won't work. I'm more interested in the behavior you find problematic, rather than the consequences of your attempt at fixing it.

My apologies. I definitely got WAY off topic here.

As for the rest of your reply, I am fairly new to Ren'py and Python in general, so it makes it hard for myself to parse more complex blocks of code like your transforms. I would like to speak privately with you on the matter so I don't annoy any potential person with a problem regarding your code. It's definitely an issue on my end and not yours.

**Comment by Gouvernathor** [comment]
You can contact me from the renpy discord server (people there know how to find me). Other than that, you should thoroughly read the renpy documentation, starting with the "Displaying images" page. And my readme :)
Also, you probably shouldn't concern yourself with *how* the code is written, which in this case is quite advanced, but rather just focus on how it's supposed to be used, as the readme and documentation explain.
